net: Vit-16

wandb: True

training:
  num_epochs: 50
  patience: 5
  lr: 0.05
  scheduler:
    step_size: 10
    gamma: 0.1
  frozen_layers: 2
  optimizer:
    momentum: 0.9
    weight_decay: 0.01

data:
  batch_size: 32
  dataset_name: competition_data
  num_classes: 100
  custom: True
  #download_url: https://data.caltech.edu/records/65de6-vp158/files/CUB_200_2011.tgz
