net: Vit-16

wandb: True

training:
  num_epochs: 50
  patience: 10
  lr: 0.05
  scheduler:
    step_size: 10
    gamma: 0.1
  frozen_layers: 0
  optimizer:
    momentum: 0.9
    weight_decay: 0.001

data:
  batch_size: 32
  dataset_name: CUB_200_2011
  num_classes: 200
  custom: True
  download_url: https://data.caltech.edu/records/65de6-vp158/files/CUB_200_2011.tgz
